eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
microservice:
  user-service:
    endpoints:
      endpoint:
        uri: http://USER-SERVICE/users/
  department-service:
    endpoints:
      endpoint:
        uri: http://DEPARTMENT-SERVICE/departments/
